-- v0.22.241
-- Add dated, explanatory normal-schedule context for peer-station pledge evidence.
-- This table does not score peer performance and must not be used as a causal adjustment.

create table if not exists public.pledge_peer_schedule_context (
  id bigint generated by default as identity primary key,
  station_code text not null,
  station_name text,
  context_period_start date not null,
  context_period_end date not null,
  day_of_week text,
  start_time_minutes integer,
  end_time_minutes integer,
  schedule_label text,
  schedule_pattern text,
  representative_programs jsonb not null default '[]'::jsonb,
  source_kind text not null default 'public_program_guide',
  source_reference text,
  source_summary text,
  evidence_strength smallint not null default 3,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pledge_peer_schedule_context_period_check
    check (context_period_end >= context_period_start),
  constraint pledge_peer_schedule_context_day_check
    check (
      day_of_week is null
      or lower(day_of_week) = any (array['monday','tuesday','wednesday','thursday','friday','saturday','sunday'])
    ),
  constraint pledge_peer_schedule_context_start_check
    check (start_time_minutes is null or (start_time_minutes >= 0 and start_time_minutes < 1440)),
  constraint pledge_peer_schedule_context_end_check
    check (end_time_minutes is null or (end_time_minutes > 0 and end_time_minutes <= 1440)),
  constraint pledge_peer_schedule_context_range_check
    check (
      start_time_minutes is null
      or end_time_minutes is null
      or end_time_minutes > start_time_minutes
    ),
  constraint pledge_peer_schedule_context_strength_check
    check (evidence_strength between 1 and 5),
  constraint pledge_peer_schedule_context_unique_source
    unique (
      station_code,
      context_period_start,
      context_period_end,
      day_of_week,
      start_time_minutes,
      end_time_minutes,
      source_reference
    )
);

comment on table public.pledge_peer_schedule_context is
  'Dated normal-schedule context for peer-station pledge evidence. Explanatory only; not a pledge-performance score.';

comment on column public.pledge_peer_schedule_context.context_period_start is
  'First date for which the cited schedule context is directly supported. Do not infer earlier continuity.';

comment on column public.pledge_peer_schedule_context.context_period_end is
  'Last date for which the cited schedule context is directly supported. Do not infer later continuity.';

comment on column public.pledge_peer_schedule_context.representative_programs is
  'Verbatim representative schedule entries from the cited source, stored as JSON objects without inferred performance.';

alter table public.pledge_peer_schedule_context enable row level security;

create policy "pledge_peer_schedule_context_read_all"
  on public.pledge_peer_schedule_context
  for select
  to anon, authenticated
  using (true);

create policy "pledge_peer_schedule_context_authenticated_insert"
  on public.pledge_peer_schedule_context
  for insert
  to authenticated
  with check (true);

create policy "pledge_peer_schedule_context_authenticated_update"
  on public.pledge_peer_schedule_context
  for update
  to authenticated
  using (true)
  with check (true);

create policy "pledge_peer_schedule_context_authenticated_delete"
  on public.pledge_peer_schedule_context
  for delete
  to authenticated
  using (true);

insert into public.pledge_peer_schedule_context (
  station_code, station_name,
  context_period_start, context_period_end,
  day_of_week, start_time_minutes, end_time_minutes,
  schedule_label, schedule_pattern, representative_programs,
  source_kind, source_reference, source_summary,
  evidence_strength, notes
)
values
(
  'SOPT',
  'Southern Oregon Public Television',
  date '2019-01-01',
  date '2019-01-31',
  'Sunday',
  540,
  720,
  'Special Presentation',
  'recurring_special_presentation_block',
  '[
    {"date":"2019-01-06","start_time":"09:00","title":"28 Day Metabolism Makeover with Amy Myers, MD"},
    {"date":"2019-01-06","start_time":"10:30","title":"Patsy Cline: American Masters"},
    {"date":"2019-01-13","start_time":"09:00","title":"The Forever Wisdom of Dr. Wayne Dyer"},
    {"date":"2019-01-20","start_time":"09:00","title":"Mindfulness Goes Mainstream"},
    {"date":"2019-01-20","start_time":"10:00","title":"Suze Orman''s Financial Solutions for You"},
    {"date":"2019-01-27","start_time":"09:00","title":"Live Better Now with Mimi Guarneri, MD"},
    {"date":"2019-01-27","start_time":"10:30","title":"Roy Orbison: Black & White Night 30"}
  ]'::jsonb,
  'public_program_guide',
  'https://dc79r36mj3c9w.cloudfront.net/prod/filer_public/soptv-bento-live-pbs/Programming%20Guides/2019/d54ec5f570_2019-01.pdf',
  'January 2019 weekly grid reserves Sunday 9:00 AM-noon as "Special Presentation." The detailed Sunday listings repeatedly use health, self-help, financial and music specials in that block.',
  5,
  'Historical schedule context only. Do not infer that this remained the station''s schedule outside January 2019.'
),
(
  'SOPT',
  'Southern Oregon Public Television',
  date '2019-06-01',
  date '2019-06-30',
  'Sunday',
  540,
  720,
  'Special Presentation',
  'recurring_special_presentation_block',
  '[
    {"date":"2019-06-02","start_time":"09:00","title":"Forever Painless with Miranda Esmonde-White"},
    {"date":"2019-06-02","start_time":"10:00","title":"Great Performances: Broadway Musicals - A Jewish Legacy"}
  ]'::jsonb,
  'public_program_guide',
  'https://dc79r36mj3c9w.cloudfront.net/prod/filer_public/soptv-bento-live-pbs/Programming%20Guides/2019/ac40904768_2019-06.pdf',
  'June 2019 weekly grid again reserves Sunday 9:00 AM-noon as "Special Presentation." On June 2 the block begins with Forever Painless followed by a Broadway music special.',
  5,
  'Historical schedule context only. Do not infer that this remained the station''s schedule outside June 2019.'
)
on conflict (
  station_code,
  context_period_start,
  context_period_end,
  day_of_week,
  start_time_minutes,
  end_time_minutes,
  source_reference
)
do update set
  station_name=excluded.station_name,
  schedule_label=excluded.schedule_label,
  schedule_pattern=excluded.schedule_pattern,
  representative_programs=excluded.representative_programs,
  source_kind=excluded.source_kind,
  source_summary=excluded.source_summary,
  evidence_strength=excluded.evidence_strength,
  notes=excluded.notes,
  updated_at=now();
