window.PLEDGE_MANAGER_CONFIG = {
  APP_NAME: 'WNMU Pledge Program Library',
  APP_VERSION: 'v0.4.0',
  SUPABASE_URL: 'https://YOUR_PROJECT.supabase.co',
  SUPABASE_ANON_KEY: 'YOUR_PUBLIC_ANON_KEY',
  ADMIN_EMAILS: [],
  DEFAULT_PAGE_SIZE: 100
};
