import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync(new URL('../assets/js/one-sheet-reports.js', import.meta.url), 'utf8');
const html = fs.readFileSync(new URL('../reports.html', import.meta.url), 'utf8');
const version = JSON.parse(fs.readFileSync(new URL('../version.json', import.meta.url), 'utf8'));

assert.equal(version.appVersion, '0.22.139');
assert.match(html, /0\.22\.139/);
assert.match(source, /function programTooltipLinesForRows/);
assert.match(source, /function aggregateProgramTooltip/);
assert.match(source, /\.map\(\(\[label, subset\]\) => \[label, subset, rankingRows\(subset, 'startTime'\)\]\)/);
assert.match(source, /sets\.flatMap\(\(\[_label, _subset, rows\]\)/);
assert.match(source, /series: sets\.map\(\(\[label, subset, rows\]\)/);
assert.match(source, /let checkingAccess = true/);
assert.match(source, /checkingAccess = false/);
assert.match(source, /Your administrator session is still valid\. This is a report-generation error, not an access failure\./);
assert.doesNotMatch(source, /showAccessDenied\(error\?\.message \|\| 'The report center could not load\.'\)/);
assert.match(source, /tooltips: productivity\.tooltips/);
assert.match(source, /tooltips: gifts\.tooltips/);
assert.match(source, /historicalTooltips/);
assert.match(source, /currentTooltips/);
assert.match(source, /tooltips: combined\.tooltips/);
assert.match(source, /stroke: '#f0c419', dash: '', width: 1\.75/);
assert.match(source, /Long-term linear trend:/);
assert.match(source, /R² \$\{trend\.r2\.toFixed\(2\)\}/);
assert.match(source, /stroke: '#ff2020', dash: '', width: 1\.1/);
assert.match(source, /least-squares line reports the long-term slope/);
assert.match(source, /HISTORICAL_EVENT_ANNOTATIONS/);
assert.match(source, /Great Recession · Dec 2007–Jun 2009/);
assert.match(source, /Federal tax-law changes · Jan 2018/);
assert.match(source, /WNMU Passport · Feb 2019/);
assert.match(source, /COVID emergency begins · Mar 2020/);
assert.match(source, /COVID emergency ends · May 2023/);
assert.match(source, /CPB funding rescinded · Jul 2025/);
assert.match(source, /function historicalEventAnnotationsForDates/);
assert.match(source, /xDateValues: productivity\.dates/);
assert.match(source, /xDateValues: gifts\.dates/);
assert.match(source, /xDateValues: seasonal\.dates/);
assert.match(source, /eventAnnotations: historicalEventAnnotationsForDates\(trend\.dates\)/);
assert.match(source, /historicalCorrespondingView: 'groups'/);
assert.match(source, /function yearHistoryBands\(analyses = \[\], bandSize = 3\)/);
assert.match(source, /yearHistoryBands\(ordered, 3\)/);
assert.match(source, /data-corresponding-view="groups"/);
assert.match(source, /data-corresponding-view="years"/);
assert.match(source, />3-Year Groups<\/button>/);
assert.match(source, />All Years<\/button>/);
assert.match(source, /view === 'years' \? 1\.15 : 1\.5/);
assert.match(source, /style: \{ stroke: '#f0c419', dash: '', width: 1\.75 \}/);
assert.match(source, /style: \{ stroke: '#ff2020', dash: '', width: 1\.1 \}/);
assert.match(source, /bindHistoricalChartControls\(\$\('#report-output'\)\)/);
assert.match(source, /const width = hasEventAnnotations \? 980 : \(crowdedChronology \? 920 : 760\)/);
assert.match(source, /const xLabelAngle = crowdedChronology \? -68 : -46/);
assert.match(source, /class=\"chart-x-label\"/);
assert.match(source, /class=\"chart-event-leader\"/);
assert.match(source, /class=\"chart-event-guide\"/);
assert.match(source, /function|const eventLabelLines/);
assert.match(source, /lines: \['WNMU Passport', 'Feb 2019'\]/);
assert.match(source, /lines: \['COVID emergency begins', 'Mar 2020'\]/);
assert.match(source, /lines: \['COVID emergency ends', 'May 2023'\]/);
assert.match(source, /lines: \['CPB funding rescinded', 'Jul 2025'\]/);
assert.match(source, /report-chart-annotated/);

assert.match(source, /function barChartSvg/);
assert.match(source, /fill-opacity=\"0\.72\"/);
assert.doesNotMatch(source, /class=\"chart-bar\"[^>]*fill=\"none\"/);
assert.match(source, /const tooltip = item\.tooltips\?\.\[index\] \|\| null/);
assert.match(source, /class=\"chart-node\" tabindex=\"0\" role=\"button\"/);
assert.match(source, /function historicalRankingTooltip/);
assert.match(source, /tooltips: rows\.map\(\(row\) => historicalRankingTooltip\(analyses, dimension, row\)\)/);
assert.match(source, /tooltips: rows\.map\(\(row\) => \{/);
assert.match(source, /incomeBarChartSvg\(days, analysis\)/);
assert.match(source, /tooltips: topics\.currentTooltips/);
assert.match(source, /tooltips: topics\.historicalTooltips/);
assert.match(source, /tooltips: programs\.tooltips/);
assert.match(source, /function topicComparisonChart\(analyses, rows\)[\s\S]*?return barChartSvg\(\{/);
assert.match(source, /className: 'topic-comparison-chart',\n      yLabel: 'Broadcast dollars'/);
assert.match(source, /function historicalStartTimeOverviewCard\(analyses = \[\]\)[\s\S]*?barChartSvg\(\{/);
assert.match(source, /async function renderHistoricalReport\([\s\S]*?bindChartTooltips\(\$\('#report-output'\)\);[\s\S]*?bindHistoricalChartControls\(\$\('#report-output'\)\);\n  \}/);

console.log('v0.22.138 chart hover, event annotation, era toggle, and trend tests passed');
