import assert from 'node:assert/strict';
import fs from 'node:fs';

const reports = fs.readFileSync(new URL('../assets/js/one-sheet-reports.js', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../assets/one-sheet-reports.css', import.meta.url), 'utf8');
const index = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const reportHtml = fs.readFileSync(new URL('../reports.html', import.meta.url), 'utf8');

assert.match(index, /dataset\.adminOnly='true'/);
assert.match(index, /textContent='Report Center'/);
assert.match(reports, /schedulePickerDetails/);
assert.match(reports, /function lineChartSvg/);
assert.match(reports, /function incomeBarChartSvg/);
assert.match(reports, /class=\"income-chart-svg\"/);
assert.match(reports, /function dailyComparisonChart/);
assert.match(reports, /function topicComparisonChart/);
assert.match(reports, /Broadcast dollars by corresponding fundraiser day/);
assert.match(reports, /Broadcast dollars by topic and non-specific giving across selected fundraisers/);
assert.match(reports, /function recurringProgramKeys/);
assert.match(reports, /Programs shown in bold aired in two or more selected fundraisers/);
assert.match(reports, /legendTop: true/);
assert.match(reports, /Select 2–5 fundraisers/);
assert.match(reports, /function programResultsTable/);
assert.match(reports, /One entry per title/);
assert.match(reports, /Program topics are ranked by Broadcast \$\/hour/);
assert.doesNotMatch(reports, /topic-rank/);
assert.match(reports, /Historical Fundraiser Analytics/);
assert.match(reports, /function isNonSpecificLabel/);
assert.match(reports, /function meaningfulMissingDurationRows/);
assert.match(reports, /Non-Specific Pledges are not treated as incomplete program\/topic data/);
assert.match(reports, /function analysesForWeekpart/);
assert.match(reports, /Weekday start-time performance/);
assert.match(reports, /Saturday start-time performance/);
assert.match(reports, /Sunday start-time performance/);
assert.doesNotMatch(reports, /Start-time performance: slots with sufficient historical evidence/);
assert.match(reports, /Continue with incomplete data/);
assert.match(reports, /Affected title/);
assert.match(reports, /function bindChartTooltips/);
assert.match(reports, /function programResultsForFundraiserDay/);
assert.match(reports, /Regional \${weatherLine\(day\)}/);
assert.match(reports, /item\.title} — \${money\(item\.dollars\)}/);
assert.match(reports, /data-chart-tooltip/);
assert.match(reports, /Return to Pledge Program Library/);
assert.match(reports, /Data Health \/ Preflight/);
assert.match(reports, /function renderPreflightReport/);
assert.match(reports, /A\.dataHealthReport/);
assert.match(reports, /<th>Day<\/th><th>Hours<\/th><th>Broadcast \$<\/th><th>\$\/hr<\/th><th>Pledges<\/th><th>Pledges\/hr<\/th><th>Regional weather<\/th>/);
assert.doesNotMatch(reports, /pledgeHourChart/);

assert.match(css, /@page\{size:letter portrait;margin:\.35in\}/);
assert.match(css, /\.sheet-section h2\{font-size:16pt/);
assert.match(css, /\.comparison-sheet \.section-heading p\{font-size:14pt/);
assert.match(css, /\.comparison-sheet \.sheet-title h1\{font-size:24pt/);
assert.match(css, /\.comparison-sheet \.report-kicker\{font-size:14pt/);
assert.match(css, /table\{font-size:9pt/);
assert.match(css, /thead th\{font-size:9pt/);
assert.match(css, /\.fundraiser-kpis strong\{font-size:13pt/);
assert.match(css, /\.report-chart svg text\{font-size:9pt/);

assert.match(reportHtml, /one-sheet-reports\.js\?v=0\.22\.115/);
assert.match(reportHtml, /one-sheet-analysis\.js\?v=0\.22\.115/);
assert.match(reportHtml, /one-sheet-reports\.css\?v=0\.22\.115/);
assert.match(reportHtml, /report-fundraiser-picker/);
assert.match(reportHtml, /report-fundraiser-trigger/);
assert.match(reportHtml, /function enhanceFundraiserPicker/);
assert.match(reportHtml, /function updatePickerSummary/);
assert.match(reportHtml, /function enhanceComparisonReport/);
assert.match(reportHtml, /function enhanceDailyMatrix/);
assert.match(reportHtml, /function enhanceTopicMatrix/);
assert.match(reportHtml, /\$ \/ Hr \(avg\)/);
assert.match(reportHtml, /Pledge hours \/ rate base/);
assert.match(reportHtml, /Total income \/ No\. pledges/);
assert.match(reportHtml, /Regional temp \/ rainfall/);
assert.match(reportHtml, /No programming within this topic occurred during this fundraiser/);
assert.doesNotMatch(reportHtml, /Excluded from \$\/hour analytics because duration is missing/);
assert.match(reportHtml, /pre-Saturday start/i);
assert.match(reportHtml, /font-size:8pt/);
assert.match(reportHtml, /font-size:13pt/);
assert.match(reportHtml, /new MutationObserver/);

console.log('one-sheet report refinements tests passed');


assert.match(reports, /A\.canonicalizeImportedAirings \? A\.canonicalizeImportedAirings\(airings\) : airings/);
assert.match(reports, /preflight-program-link/);
assert.match(reports, /Superseded imported observations/);
assert.match(reportHtml, /one-sheet-analysis\.js\?v=0\.22\.115/);
assert.match(reportHtml, /one-sheet-reports\.js\?v=0\.22\.115/);


assert.match(reports, /data-preflight-program-id/);
assert.match(reports, /function openPreflightProgramEditor/);
assert.match(reports, /preflight-program-editor-frame/);
assert.match(reports, /detailOnly=1/);
assert.match(reports, /Close & refresh Preflight/);
assert.match(reports, /preflight-mismatch-tag/);
assert.doesNotMatch(reports, /class=\"preflight-program-link\" href=/);
assert.match(index, /const DETAIL_ONLY=/);
assert.match(index, /library-detail-only/);
assert.match(index, /#detail-close-button\{display:none!important\}/);
assert.match(css, /\.preflight-program-editor-backdrop\{/);
