import assert from 'node:assert/strict';
import fs from 'node:fs';

const reports = fs.readFileSync(new URL('../assets/js/one-sheet-reports.js', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../assets/one-sheet-reports.css', import.meta.url), 'utf8');
const index = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const reportHtml = fs.readFileSync(new URL('../reports.html', import.meta.url), 'utf8');

assert.match(index, /data\.adminOnly='true'/);
assert.match(index, /textContent='Report Center'/);
assert.match(reports, /schedulePickerDetails/);
assert.match(reports, /function lineChartSvg/);
assert.match(reports, /function incomeBarChartSvg/);
assert.match(reports, /class=\"income-chart-svg\"/);
assert.match(reports, /function dailyComparisonChart/);
assert.match(reports, /function topicComparisonChart/);
assert.match(reports, /Broadcast dollars by corresponding fundraiser day/);
assert.match(reports, /Broadcast dollars by topic across selected fundraisers/);
assert.match(reports, /function recurringProgramKeys/);
assert.match(reports, /Programs shown in bold aired in two or more selected fundraisers/);
assert.match(reports, /legendTop: true/);
assert.match(reports, /Select 2–5 fundraisers/);
assert.match(reports, /function programResultsTable/);
assert.match(reports, /One entry per title/);
assert.match(reports, /Topics are ranked by Broadcast \$\/hour/);
assert.doesNotMatch(reports, /topic-rank/);
assert.match(reports, /Historical Fundraiser Analytics/);
assert.match(reports, /function isNonSpecificLabel/);
assert.match(reports, /function meaningfulMissingDurationRows/);
assert.match(reports, /Non-Specific Pledges are not treated as incomplete program\/topic data/);
assert.match(reports, /function analysesForWeekpart/);
assert.match(reports, /Weekday start-time performance/);
assert.match(reports, /Saturday start-time performance/);
assert.match(reports, /Sunday start-time performance/);
assert.doesNotMatch(reports, /Start-time performance: slots with sufficient historical evidence/);
assert.match(reports, /Continue with incomplete data/);
assert.match(reports, /Return to Pledge Program Library/);
assert.match(reports, /<th>Day<\/th><th>Hours<\/th><th>Broadcast \$<\/th><th>\$\/hr<\/th><th>Pledges<\/th><th>Pledges\/hr<\/th><th>Weather<\/th>/);
assert.doesNotMatch(reports, /pledgeHourChart/);

assert.match(css, /@page\{size:letter portrait;margin:\.35in\}/);
assert.match(css, /\.sheet-section h2\{font-size:16pt/);
assert.match(css, /\.comparison-sheet \.section-heading p\{font-size:14pt/);
assert.match(css, /\.comparison-sheet \.sheet-title h1\{font-size:24pt/);
assert.match(css, /\.comparison-sheet \.report-kicker\{font-size:14pt/);
assert.match(css, /table\{font-size:9pt/);
assert.match(css, /thead th\{font-size:9pt/);
assert.match(css, /\.fundraiser-kpis strong\{font-size:13pt/);
assert.match(css, /\.report-chart svg text\{font-size:9pt/);
const printCss = css.slice(css.indexOf('@media print'));
assert.doesNotMatch(printCss, /font-size:[0-8](?:\.\d+)?pt/, 'print styles must not use type smaller than 9pt');
assert.match(reportHtml, /one-sheet-reports\.js\?v=0\.22\.105/);
assert.match(reportHtml, /one-sheet-analysis\.js\?v=0\.22\.105/);
assert.match(reportHtml, /one-sheet-reports\.css\?v=0\.22\.105/);
assert.match(reportHtml, /report-fundraiser-picker/);
assert.match(reportHtml, /report-fundraiser-trigger/);
assert.match(reportHtml, /function enhanceFundraiserPicker/);
assert.match(reportHtml, /function updatePickerSummary/);
assert.match(reportHtml, /MutationObserver\(enhanceFundraiserPicker\)/);

console.log('one-sheet report refinements tests passed');
