from pathlib import Path
import json

ROOT = Path('.')

def replace_once(path, old, new):
    text = path.read_text()
    if old not in text:
        raise SystemExit(f'missing expected block in {path}: {old[:140]!r}')
    if text.count(old) != 1:
        raise SystemExit(f'expected one match in {path}, found {text.count(old)}')
    path.write_text(text.replace(old, new, 1))

data = ROOT / 'assets/js/data.js'
loader = ROOT / 'assets/js/library-load.js'
version = ROOT / 'version.json'
test = ROOT / 'tests/library-load-performance.test.mjs'

old_refresh = '''  async function refreshRawRows() {\n    const source = await chooseLibrarySource();\n    let baseRows = [];\n    let summaryRows = [];\n\n    if (state.baseSource?.okay) {\n      try {\n        baseRows = await fetchAllRows(constants.BASE_TABLE);\n      } catch (error) {\n        console.warn('Canonical base-table fetch failed.', error);\n      }\n    }\n    if (state.summarySource?.okay) {\n      try {\n        summaryRows = await fetchAllRows(constants.LIBRARY_VIEW);\n      } catch (error) {\n        console.warn('Summary enrichment fetch failed.', error);\n      }\n    }\n\n    let mergedRows = [];\n    if (!baseRows.length && source.name === constants.LIBRARY_VIEW && summaryRows.length) {\n      state.baseRows = [];\n      mergedRows = mergeLibraryRows([], summaryRows);\n      state.rawRows = mergedRows;\n    } else {\n      state.baseRows = baseRows;\n      mergedRows = mergeLibraryRows(baseRows, summaryRows);\n      state.rawRows = mergedRows;\n    }\n\n    try {\n      const airingsRows = await fetchAllRows(constants.AIRINGS_TABLE);\n      const historyIndex = buildAiringHistoryIndex(airingsRows);\n      state.baseRows = attachAiringHistory(state.baseRows, historyIndex);\n      state.rawRows = attachAiringHistory(mergedRows, historyIndex);\n    } catch (error) {\n      console.warn('Air-date history enrichment failed.', error);\n    }\n    state.fieldAudit = buildFieldAudit(state.rawRows);\n    resetDetailCaches();\n    return state.rawRows;\n  }\n'''
new_refresh = '''  let libraryAiringHistoryPromise = null;\n\n  function applyLibraryAiringHistory(airingsRows = []) {\n    const historyIndex = buildAiringHistoryIndex(airingsRows);\n    state.baseRows = attachAiringHistory(state.baseRows, historyIndex);\n    state.rawRows = attachAiringHistory(state.rawRows, historyIndex);\n    return state.rawRows;\n  }\n\n  async function refreshAiringHistory() {\n    const sharedRows = Array.isArray(state.scheduleImportedAiringsCache)\n      ? state.scheduleImportedAiringsCache\n      : null;\n    if (sharedRows) return applyLibraryAiringHistory(sharedRows);\n    if (libraryAiringHistoryPromise) return libraryAiringHistoryPromise;\n\n    libraryAiringHistoryPromise = (async () => {\n      const airingsRows = await fetchAllRows(constants.AIRINGS_TABLE);\n      return applyLibraryAiringHistory(airingsRows);\n    })();\n\n    try {\n      return await libraryAiringHistoryPromise;\n    } finally {\n      libraryAiringHistoryPromise = null;\n    }\n  }\n\n  async function refreshRawRows() {\n    const source = await chooseLibrarySource();\n    let baseRows = [];\n    let summaryRows = [];\n\n    if (state.baseSource?.okay) {\n      try {\n        baseRows = await fetchAllRows(constants.BASE_TABLE);\n      } catch (error) {\n        console.warn('Canonical base-table fetch failed.', error);\n      }\n    }\n    if (state.summarySource?.okay) {\n      try {\n        summaryRows = await fetchAllRows(constants.LIBRARY_VIEW);\n      } catch (error) {\n        console.warn('Summary enrichment fetch failed.', error);\n      }\n    }\n\n    let mergedRows = [];\n    if (!baseRows.length && source.name === constants.LIBRARY_VIEW && summaryRows.length) {\n      state.baseRows = [];\n      mergedRows = mergeLibraryRows([], summaryRows);\n      state.rawRows = mergedRows;\n    } else {\n      state.baseRows = baseRows;\n      mergedRows = mergeLibraryRows(baseRows, summaryRows);\n      state.rawRows = mergedRows;\n    }\n\n    state.fieldAudit = buildFieldAudit(state.rawRows);\n    resetDetailCaches();\n    return state.rawRows;\n  }\n'''
replace_once(data, old_refresh, new_refresh)
replace_once(data, '''    chooseLibrarySource,\n    refreshRawRows,\n    getProbeStatusMessage,\n''', '''    chooseLibrarySource,\n    refreshRawRows,\n    refreshAiringHistory,\n    getProbeStatusMessage,\n''')

old_after_workspace = '''      } else if (activeWorkspace === 'performance' && state.performance?.ready) {\n        await App.performanceUi?.refreshData({ silent: true });\n        App.performanceUi?.populateControls();\n        App.performanceUi?.renderAll();\n      }\n\n      const probeStatus = App.data.getProbeStatusMessage();\n'''
new_after_workspace = '''      } else if (activeWorkspace === 'performance' && state.performance?.ready) {\n        await App.performanceUi?.refreshData({ silent: true });\n        App.performanceUi?.populateControls();\n        App.performanceUi?.renderAll();\n      }\n\n      const historyRefresh = App.data.refreshAiringHistory?.();\n      if (historyRefresh?.then) {\n        historyRefresh.then(() => {\n          App.listUi.buildFilterOptions();\n          App.listUi.applyLibraryView();\n          App.workspaceUi?.refreshScaffoldSummary();\n        }).catch((error) => {\n          console.warn('Background air-date history enrichment failed.', error);\n        });\n      }\n\n      const probeStatus = App.data.getProbeStatusMessage();\n'''
replace_once(loader, old_after_workspace, new_after_workspace)
replace_once(loader, '''      setNotice(`Loaded ${utils.formatCount(state.rawRows.length)} source rows. Scheduling title match is ready.`);\n''', '''      setNotice(`Loaded ${utils.formatCount(state.rawRows.length)} source rows. Air-date history is updating in the background.`);\n''')

payload = json.loads(version.read_text())
payload['appVersion'] = '0.22.112'
payload['releasedAt'] = '2026-08-31'
version.write_text(json.dumps(payload, separators=(',', ':')) + '\n')

test.write_text('''import assert from 'node:assert/strict';\nimport fs from 'node:fs';\n\nconst data = fs.readFileSync(new URL('../assets/js/data.js', import.meta.url), 'utf8');\nconst loader = fs.readFileSync(new URL('../assets/js/library-load.js', import.meta.url), 'utf8');\nconst version = JSON.parse(fs.readFileSync(new URL('../version.json', import.meta.url), 'utf8'));\n\nconst rawStart = data.indexOf('async function refreshRawRows()');\nconst rawEnd = data.indexOf('\\n  function getProbeStatusMessage', rawStart);\nassert.ok(rawStart >= 0 && rawEnd > rawStart, 'refreshRawRows source block should exist');\nconst rawBlock = data.slice(rawStart, rawEnd);\nassert.doesNotMatch(rawBlock, /AIRINGS_TABLE/, 'initial Program Library rows must not wait for imported airing history');\nassert.match(data, /async function refreshAiringHistory\(\)/);\nassert.match(data, /fetchAllRows\(constants\.AIRINGS_TABLE\)/);\nassert.match(data, /Array\.isArray\(state\.scheduleImportedAiringsCache\)/);\nassert.match(loader, /const historyRefresh = App\.data\.refreshAiringHistory\?\.\(\);/);\nassert.doesNotMatch(loader, /await App\.data\.refreshAiringHistory/);\nassert.match(loader, /Air-date history is updating in the background/);\nassert.equal(version.appVersion, '0.22.112');\n\nconsole.log('library fast-load tests passed');\n''')

print('v0.22.112 fast-load patch applied')
